Gemfile
Gemfile.lock
app/models/user.rb
app/views/shared/_navbar.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20171010211827_devise_create_users.rb
db/schema.rb
spec/models/user_spec.rb

Base User and Devise install

---

Gemfile
Gemfile.lock
app/models/floor.rb
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20171024181715_create_floors.rb
db/migrate/20171024182929_add_attachment_map_to_floors.rb
db/schema.rb
spec/models/floor_spec.rb

Fix #56 
Fix #52 
Fix #51 
Fix #50

Creates floor in db, Installs paperclip, Adds floor with paperclip upload to rails admin

---

config/deploy.rb
config/initializers/rails_admin.rb
db/seeds.rb
lib/capistrano/tasks/seed.rake

Creates floor seeds and sets up auto seed on deploy and disables floor create/delete

---

app/models/location.rb
app/models/trait.rb
config/initializers/rails_admin.rb
db/migrate/20171030152039_add_trait_to_locations.rb
db/schema.rb

Changes relationship to allow multiple locations for a single trait.

---

app/assets/stylesheets/_floor_index.scss
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/application.scss
app/controllers/floors_controller.rb
app/helpers/floor_helper.rb
app/views/floors/_floor_pane.html.erb
app/views/floors/_floor_select_panel.html.erb
app/views/floors/index.html.erb
config/routes.rb

Creates floor index page, makes floors#index the root page

---

app/assets/stylesheets/_login.scss
app/assets/stylesheets/application.scss
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/locales/en.yml
lib/templates/erb/scaffold/_form.html.erb

Fix #40 
Also generated views for devise to allow editing within the app and set up simpleform to use bootstrap styling.

Sets up prettier login form

---

db/migrate/20171107185608_add_position_values_to_floor.rb
db/migrate/20171107185904_add_position_x_and_position_y_to_locations.rb
db/schema.rb

Adds position values to floor and Location

---

Gemfile
Gemfile.lock
app/models/tag.rb

Integrates basic search functionality into project.

Adds searching library to the application

---

app/models/icon.rb
app/models/location.rb
db/migrate/20180112223736_create_icons.rb
db/migrate/20180112224539_add_icon_image_to_icon.rb
db/migrate/20180112232254_add_icon_id_to_location.rb
db/schema.rb
spec/models/icon_spec.rb

Adds icon, icon image, relavent migrations etc.

---

app/models/floor.rb
app/models/icon.rb
app/models/location.rb
app/models/tag.rb
app/models/trait.rb
app/models/trait_type.rb
app/models/user.rb
config/initializers/rails_admin.rb
db/seeds.rb
spec/models/trait_type_spec.rb

fixes linting style problems
fixes User admin experience
trait type no longer needed
adds validations, moves rails_admin configurations to models

refactors and cleanup

---

app/models/icon.rb
app/models/location.rb
db/migrate/20180116220915_add_name_to_icon.rb
db/schema.rb
db/seeds.rb

This adds the "name" attribute to an icon, changes it to being optional on locations. Updates the location to use the floor id rather.

Fixes seed data and configures icon with more info

---

app/assets/images/Map_1.svg
app/assets/images/Map_2.svg
app/assets/images/Map_3.svg
app/assets/images/Map_4.svg
app/assets/images/Map_5.svg
app/assets/images/Map_6.svg
app/models/floor.rb
db/seeds.rb

fixes initial seed data to include maps

---

app/javascript/stylesheets/_floor_index.scss
app/javascript/stylesheets/_navbar.scss

This resolves the style issues.

Fixes modal and nav styles

---

app/controllers/floors_controller.rb
app/javascript/components/MapAndButtons.js
app/javascript/components/MapView.js
app/models/location.rb
app/views/floors/index.html.erb
app/views/floors/index.json.jbuilder

This adds icons into the map and rendering an icon for each location that has an icon. We have to build out a hash that contains the icon id as well as the path so for each location, we can inspect its icon id and render the proper icon. Works for both persistent and non persistent locations.

Renders the icon as an image with same data

---

app/controllers/floors_controller.rb
app/models/floor.rb
app/models/location.rb
app/views/floors/index.html.erb
config/routes.rb

refactors toward an initial application state

---

app/javascript/components/LocationBox.jsx
app/javascript/components/MapEdit.jsx
app/javascript/stylesheets/_map_edit.scss
app/models/location.rb

fixes #124 
with some refactors too

adds edit button for rendered locations

---

app/controllers/floors_controller.rb
app/javascript/components/MapAndButtons.js
app/javascript/components/MapView.js
app/models/floor.rb
app/models/icon.rb
app/models/label.rb
app/models/location.rb
app/models/location_icon.rb
app/models/location_label.rb
app/views/floors/index.html.erb
app/views/floors/index.json.jbuilder
config/initializers/rails_admin.rb
db/migrate/20180118211633_create_location_icons.rb
db/migrate/20180118211642_create_location_labels.rb
db/migrate/20180118211652_create_labels.rb
db/migrate/20180118212925_add_location_id_and_icon_id_to_location_icon.rb
db/migrate/20180118214216_add_location_id_and_label_id_to_location_labels.rb
db/schema.rb
spec/models/label_spec.rb
spec/models/location_icon_spec.rb
spec/models/location_label_spec.rb

Adds labels into the application and changes icon.

---

.rspec
app/controllers/api/api_controller.rb
app/controllers/api/locate_controller.rb
app/controllers/application_controller.rb
config/alma_location_map.yml
config/local_env.example.yml
config/routes.rb
spec/controllers/api/locate_controller_spec.rb

Locate link api

---

app/javascript/components/MapAndButtons.js
app/javascript/components/MapEdit.jsx
app/javascript/components/MapView.js
app/javascript/stylesheets/_floor_index.scss

fixes #206 
fixes #205 
fixes some funky style (adds padding to left and right of main page), moves administrator buttons (edit, save, exit) to beneath accordion on the right

Map positioning fixes

---

app/javascript/components/LocationBox.jsx

open location rails_admin link in a new tab

---

app/javascript/components/LocationBox.jsx
app/javascript/components/MapEdit.jsx
app/javascript/components/MapView.jsx

gives better experience with rendering and placing icon locations on the map

---

app/models/floor.rb
app/models/icon.rb
app/models/label.rb

Fixes #193 
Fixes #195 
Fixes #196

Validations for models

---

app/models/user.rb

Stops current user from updating own admin status

---

app/models/label.rb
app/models/location.rb
db/migrate/20180213194031_add_label_id_to_location.rb
db/schema.rb

Fixes label and icon saving issues

---

app/controllers/floors_controller.rb
app/javascript/components/FloorButton.jsx
app/javascript/components/LocationBox.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/components/MapEdit.jsx
app/javascript/components/MapView.jsx
app/javascript/stylesheets/_floor_index.scss
app/javascript/stylesheets/_map.scss
app/javascript/stylesheets/application.scss
app/views/floors/index.html.erb
db/migrate/20180213035201_add_text_positioning_to_location.rb
db/schema.rb

fixes #199 
fixes #200 
fixes #197

updates standardizes on locationbox for rendering view and edit

---

app/models/icon.rb
db/schema.rb

Uses proper thumb method and paperclip for rails admin

---

app/controllers/floors_controller.rb
app/javascript/components/LocationBox.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/components/MapEdit.jsx
app/javascript/components/MapEditButtons.jsx
app/javascript/components/SaveButton.jsx

handles success and failure state with mass save capability

---

app/controllers/floors_controller.rb
app/javascript/components/LocationBox.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/components/MapEdit.jsx
app/javascript/stylesheets/_map.scss
config/routes.rb

delete location functionality

---

app/javascript/components/LocationBox.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/components/MapEdit.jsx
app/javascript/components/NotificationList.jsx
app/javascript/components/NotificationListItem.jsx
app/javascript/stylesheets/_floor_index.scss

displays an error alert to show when locations failed to save

---

config/database.yml
config/local_env.example.yml

updates to use database configurations for staging and production

---

app/javascript/components/MapAndButtons.jsx
app/javascript/components/MapView.jsx

update mapview state to use editted-locations if they exist

---

app/controllers/floors_controller.rb
app/models/tag.rb
app/models/trait.rb

fixes bugs with current_user and with search

---

app/controllers/floors_controller.rb
app/javascript/components/AddLocation.jsx
app/javascript/components/Location.js
app/javascript/components/LocationBox/LocationBox.jsx
app/javascript/components/MapView.jsx
app/models/label.rb
app/models/location.rb

add a label while creating a new location

---

app/controllers/floors_controller.rb
app/javascript/components/AddLocation.jsx
app/javascript/components/Location.js
app/javascript/components/LocationBox/LocationBox.jsx
app/javascript/components/LocationBox/SavingIndicator.jsx
app/javascript/components/MapEditButtons.jsx
app/javascript/stylesheets/_add_location.scss
app/javascript/stylesheets/_floor_index.scss
app/javascript/stylesheets/_map.scss
app/javascript/stylesheets/application.scss
app/models/icon.rb

Location edit add icon

---

app/javascript/components/MapEdit.jsx
app/javascript/components/MapView.jsx

renders SVG maps in Firefox

---

app/models/tag.rb

Makes tag unique

---

app/models/icon.rb

Allows svg for icons

---

app/javascript/components/Legend.jsx
app/javascript/components/MapAndButtons.jsx

Fixes #266 
Relates #262 
Fixes #268

Moves and formats legend into two column layout.

---

app/javascript/components/LegendListElement.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/stylesheets/_floor_index.scss
app/javascript/stylesheets/_map.scss

Adds HTML and CSS for updated legend view

---

app/controllers/floors_controller.rb
app/javascript/components/Location.js
app/javascript/components/LocationBox/LocationBox.jsx
app/models/location.rb
db/migrate/20180309183139_add_icon_position_to_location.rb
db/schema.rb

Adds draggable icons

---

app/javascript/components/MapView.jsx

Fixes a bug with filtering searched locations out of persistent locations

Fixes bug in logic of filtering out searched locations from persistent ones

---

package.json
yarn.lock

updates yarn package to a fork with bugfix virtual-keyboard

---

app/controllers/floors_controller.rb

checks if a valid search was there

---

app/javascript/components/Legend.jsx

Toggle legend off if no icons present

---

app/controllers/floors_controller.rb
app/javascript/components/Legend.jsx
app/javascript/components/MapAndButtons.jsx
config/initializers/rails_admin.rb

Adds flash notice to view

---

app/javascript/components/LegendListElement.jsx

Fixes if statements

---

config/initializers/rails_admin.rb

Cant add new icons through interface

---

app/controllers/floors_controller.rb

Allows icons to be saved

---

app/controllers/floors_controller.rb
app/javascript/components/Location.js
app/javascript/components/LocationBox/LocationBox.jsx

Locations werent fully saving properly if no icon was present. Also hides icon if it doesn't exist.

Fixes issue with icon displaying when not present and saving depending on icon or not

---

app/controllers/floors_controller.rb
app/javascript/components/AddLocation.jsx

Unselects icon

---

app/javascript/components/MapAndButtons.jsx

Switches floor to search result floor if one hit

---

app/controllers/floors_controller.rb

Adds notification for no results found

---

app/controllers/floors_controller.rb
app/javascript/components/FlashMessages.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/components/MapView.jsx
app/javascript/stylesheets/_map.scss

fixes flash messaging and improves search result visibility

---

app/controllers/floors_controller.rb
app/javascript/components/Location.js

fixes location search count and highlighting logic

---

app/javascript/stylesheets/application.scss
app/javascript/stylesheets/bootstrap-collapse-animation.scss
app/views/shared/_search_nav.html.erb

Remove search bar unless search button clicked

---

app/controllers/floors_controller.rb
app/javascript/components/Legend.jsx
app/javascript/components/LegendListElement.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/stylesheets/_floor_index.scss
app/javascript/stylesheets/_map.scss

added active_search state to keep track of selected legend list element

---

app/javascript/components/LegendListElement.jsx
app/javascript/components/MapAndButtons.jsx
app/javascript/stylesheets/_floor_index.scss

moved floor buttons to left sidebar

---

Gemfile
Gemfile.lock
package.json
yarn.lock

Security alert identified Bootstrap as having needing update to 4.1.2

updates bootstrap gem and node module for security

---

Gemfile
Gemfile.lock

updates vulnerable gems and their dependencies

gem updates identified by security audit
